name = "LNR"
uuid = "7c4cb9fa-83a0-5386-9231-d6167c818060"
version = "0.2.1"

[deps]
Compat = "34da2185-b29b-5c13-b0c7-acf172513d20"
Lazy = "50d2b5c4-7a5e-59d5-8109-a42b560f39c0"

[compat]
julia = "0.7, 1"
Compat = "1, 2, 3"
Lazy = "0.13, 0.14, 0.15"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
